dist: trusty
language: python

python:
  - "2.7"

install:
  - sh ckanext/status/tests/bin/build.sh

services:
  - redis-server
  - postgresql

addons:
  postgresql: "9.4"

script: coverage run --source=ckanext.status setup.py nosetests --ckan --with-pylons=ckanext/status/tests/bin/test.ini --nologcapture --debug=ckantest,ckanext.status --rednose

after_success: coveralls
